config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, allow_blank: false
  validates :address, presence: true, allow_blank: false
  validates :category, presence: true, allow_blank: false, inclusion: { in: %w(chinese italian japanese french belgian)} 
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [ :show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else 
      render :new
    end 
  end

  def edit 
  end

  def update 
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurant_path
  end

  private 

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params 
    params.require(:restaurant).permit(:name, :category, :address)
  end 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [ :show, :edit, :update, :destroy]

  def index
    @reviews = Review.all
  end 

  def new 
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end 

  def show
  end 

  def create 
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end 
  end

  def edit
  end 

  def update
    @review.save(review_params)
    redirect_to restaurant_path(@review.restaurant)
  end 

  def destroy 
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end 

  private

  def find_review
    @review = Review.find(params[:id])
  end 

  def review_params 
    params.require(:review).permit(:content, :rating)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for [ @restaurant ] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.submit %>
<% end  %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
<% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant_path(restaurant) %>
  <%= link_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
<% end %>
</ul>

<%= link_to "Create New Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Create a restaurant</h1>

<%= render "form" %>

<%= link_to "Back to Restaurants", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.category %></h2>

<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/_form.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit %>
<% end  %>

app/views/reviews/index.html.erb
<h1><%= @restaurant.name %>Reviews</h1>

<ul>
<% @reviews.each do |review| %>
  <li>
    <%= review.content %>
    <%= review.rating %>
  </li>
<% end %>
</ul>

app/views/reviews/new.html.erb
<h1>Create a review</h1>

<%= render "form" %>

app/views/reviews/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @review.rating %></p>
<p><%= @review.content %></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>